Vagrant.configure("2") do |config|

  config.vm.define "ts.elastomic" do |cfg|
    cfg.vm.box = "mocyber/elastomic"
    cfg.vm.box_version = "0.2"
    cfg.vm.hostname = "elk"
    cfg.disksize.size = "256GB"
    #cfg.vbguest.auto_update = false
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.33.10", auto_config: true
    cfg.vm.network "forwarded_port", guest: 5601, host: 5601
    cfg.vm.network "forwarded_port", guest: 9200, host: 9200
    cfg.vm.network "forwarded_port", guest: 8487, host: 8487
    cfg.vm.network "forwarded_port", guest: 8888, host: 8888
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "elastomic"
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    cfg.vm.provision "loadprebuiltrules", type: "shell", path: "./scripts/siem-prebuilt-rules.sh"
    end
  end

  config.vm.define "ts.windows10" do |cfg|
    cfg.vm.box = "mocyber/windows10"
    cfg.vm.box_version = "0.3"
    cfg.vm.hostname = "win10"
    cfg.vm.network "private_network", ip: "192.168.33.11", auto_config: true
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "windows10"
      vb.memory = 2048
      vb.cpus = 2
    cfg.vm.provision "exprfix", type: "shell", path: "./scripts/fix-windows-expiration.ps1"
    cfg.vm.provision "shutup10", type: "shell", path: "./scripts/install-shutup10config.ps1"
    cfg.vm.provision "installea", type: "shell", path: "./scripts/install-ea.ps1"
    end
  end

  config.vm.define "ts.centos7" do |cfg|
    cfg.vm.box = "mocyber/centos"
    cfg.vm.box_version = "0.1"
    cfg.vm.hostname = "centos"
    cfg.vm.synced_folder '.', '/vagrant', disabled: true
    cfg.vm.network "private_network", ip: "192.168.33.12", auto_config: true
    cfg.vm.network "forwarded_port", guest: 80, host: 8080
    cfg.vm.network "forwarded_port", guest: 9090, host: 9090
    cfg.vm.provider :virtualbox do |vb|
      vb.name = "centos"
      vb.memory = 1024
      vb.cpus = 1
      vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    cfg.vm.provision "auditbeatsetup", type: "shell", path: "./scripts/setup-linux-beats.sh"
    end
  end
end
