---
  - hosts: all
    become: yes
    gather_facts: no

    tasks:
  
    - name: Import RPM Keys
      rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        - https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: Add EPEL Repository
      yum:
        name: epel-release

    - name: Add Elastic Repository
      yum_repository:
        name: elastic
        description: Elasticsearch repository for 7.x packages
        enabled: yes
        gpgcheck: yes
        baseurl: https://artifacts.elastic.co/packages/7.x/yum
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        file: elastic

    - name: Add Microsoft Repository
      yum_repository:
        name: packages-microsoft-com-prod
        description: Microsoft Repo for RHEL-based
        enabled: yes
        gpgcheck: yes
        baseurl: https://packages.microsoft.com/rhel/7/prod/
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        file: prod

    - name: Clean Yum Cache
      command: yum clean all

    - name: Install System Tools
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - nano
          - tmux
          - cockpit
          - git
          - wget
          - golang
          - bzip2

    - name: Start Firewalld Service
      systemd:
        name: firewalld
        state: started
        enabled: yes

###################################
# Cockpit
###################################

    - name: Add Cockpit Firewall Rule
      firewalld:
        zone: public
        port: 9090/tcp
        permanent: yes
        immediate: yes
        state: enabled

    - name: Install Cockpit
      yum: 
        name: cockpit
        state: present

    - name: Enable Cockpit Service
      systemd: 
        name: cockpit
        state: started
        enabled: yes


###################################
# Web Server
###################################

    - name: Install Nginx Webserver
      yum: 
        name: nginx
        state: present

    - name: Start & Enable Nginx Webserver
      systemd: 
        name: nginx
        state: started
        enabled: yes
    
    - name: Add Nginx Firewall Rule
      firewalld:
        zone: public
        service: http
        permanent: yes
        immediate: yes
        state: enabled


####################################
# Auditd
###################################

    - name: Copy Auditd Configuration
      copy:
        src: ./files/audit.rules
        dest: /etc/audit/audit.rules
        owner: root
        group: root
        mode: '0700'

    - name: Stop Auditd Service
      command: service auditd stop
  
    - name: Disable Auditd Service
      systemd:
        name: auditd
        enabled: no


###################################
# Syslog Server
###################################

    - name: Install Rsyslog
      yum:
        name: rsyslog
        state: present

    - name: Start and Enable Rsyslog
      systemd: 
        name: rsyslog
        state: started
        enabled: yes


###################################
# Samba Server
# Initial effort is anonymous file sharing
###################################

    - name: Install Samba Server
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - samba
          - samba-client
          - samba-common
    
    - name: Start & Enable SMB Service
      systemd: 
        name: smb
        state: started
        enabled: yes
        
    - name: Start & Enable NMB Service
      systemd: 
        name: nmb
        state: started
        enabled: yes

    - name: Add Samba Firewall Rule
      firewalld:
        zone: public
        service: samba
        permanent: yes
        immediate: yes
        state: enabled
    
    - name: Create Samba Share Directory
      file:
        path: /srv/samba/anonymous
        state: directory
        mode: '0755'
        owner: nobody
        group: nobody

    - name: Configure Samba
      copy:
        src: ./files/smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0544'

    - name: Copy Data to SMB Share
      copy:
        src: ./files/executive-credentials.secret
        dest: /srv/samba/anonymous
        
    - name: Set SELinux Context on Samba Share
      command: chcon -Rt samba_share_t /srv/samba/anonymous


###################################
# Filebeat
###################################

    - name: Install Filebeat
      yum:
        name: filebeat
        state: present    

    - name: Copy Filebeat Configuration
      copy:
        src: ./files/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0600'

    - name: Enable Filebeat Modules
      command: "filebeat modules enable nginx system"

    # - name: Run Filebeat Setup
    #   command: "filebeat setup"

    - name: Start & Enable Filebeat
      systemd:
        name: filebeat
        state: started
        enabled: yes    


###################################
# Auditbeat
###################################

    - name: Install Auditbeat
      yum:
        name: auditbeat
        state: present

    - name: Copy Auditbeat Configuration
      copy:
        src: ./files/auditbeat.yml
        dest: /etc/auditbeat/auditbeat.yml
        owner: root
        group: root
        mode: '0600'

    # - name: Run Auditbeat Setup
    #   command: auditbeat setup --dashboards

    - name: Start & Enable Auditbeat
      systemd:
        name: auditbeat
        state: started
        enabled: yes


###################################
# Powershell
###################################

    - name: Install Powershell
      yum:
        name: powershell
        state: present

    - name: Enable Powershell Remoting
      command: pwsh -Command {Enable-PSRemoting -Force}


###################################
# SSH Configuration
###################################

    - name: Uncomment Pass Auth Yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication\s+yes'
        line: PasswordAuthentication yes
        owner: root
        group: root
        mode: '0600'

    - name: Comment out Passauth No
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication\s+no'
        line: '# PasswordAuthentication no'
        owner: root
        group: root
        mode: '0600'

    - name: Allow SSH Pubkey Auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication\s+yes'
        line: 'PubkeyAuthentication yes'
        owner: root
        group: root
        mode: '0600'

    - name: Add PS Subsystem to PS remote over SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'Subsystem powershell /usr/bin/pwsh -sshs -NoLogo'
        create: yes
        owner: root
        group: root
        mode: '0600'

    - name: Create Vagrant User SSH Directory
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        mode: '0700'

    - name: Retrieve Default Vagrant Pub Key
      command: wget --no-check-certificate https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/authorized_keys

    # - name: Copy Authorizedkeys File
    #   copy:
    #     src: ./files/authorizedkeys
    #     dest: /home/vagrant/.ssh/authorizedkeys
    #     owner: vagrant
    #     group: vagrant
    #     mode: '0600'
  
    - name: Update Permissions of SSH Key
      file:
        path: /home/vagrant/.ssh/authorized_keys
        state: file
        owner: vagrant
        mode: '0600'
  
    - name: Add AuthorizedKeysFile to Config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AuthorizedKeysFile\s+\.ssh/authorized_keys'
        line: 'AuthorizedKeysFile %h/.ssh/authorized_keys'
        owner: root
        group: root
        mode: '0600'

    - name: Restart sshd service
      systemd:
        name: sshd
        state: restarted
