# This is a basic workflow to help you get started with Actions

name: Build Centos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
  schedule:
    - cron: '0 7 * * mon' # every monday at 1am local


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel          
jobs:
  packer:
    runs-on: self-hosted
    name: packer

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          ref: actions-centos

      - name: Validate packer file syntax
        run: ./packer/packer-validate-centos.sh
        # working-directory: ./packer

      - name: Build local and cloud boxes
        env:
          VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }} 
        run: ./packer/packer-build-centos.sh
        # working-directory: ./packer

#       - name: Upload local box to webshare (or bucket)
#         run: xxx